---
- name: "Ensure required parameters are provided."
  ansible.builtin.assert:
    that:
      - jws_home is defined
      - jws_listen_http_port is defined
      - jws_listen_https_port is defined
      - jws_listen_ajp_port is defined
      - jws_shutdown_port is defined
    quiet: True

- name: Load metadata on selinux policy file
  become: "{{ jws_selinux_policy_require_priv_escalation }}"
  ansible.builtin.stat:
    path: "{{ jws_home }}/selinux/jws{{ jws_version.split('.')[0] | default('6') }}-tomcat.if"
  register: archive_path_selinux

- name: "Compile and install selinux policy"
  when: archive_path_selinux.stat.exists
  become: "{{ jws_selinux_policy_require_priv_escalation }}"
  block:
    - name: Install selinux-policy-devel
      ansible.builtin.include_tasks: ../fastpackage.yml
      vars:
        packages_list:
          - selinux-policy-devel

    - name: Check if archive contains a selinux policy
      become: True
      ansible.builtin.stat:
        path: "{{ jws_home }}/selinux/jws{{ jws_version.split('.')[0] | default('6') }}-tomcat.pp"
      register: policy_path_selinux

    - name: Update file contexts with home directory
      become: True
      ansible.builtin.replace:
        path: "{{ jws_home }}/selinux/jws{{ jws_version.split('.')[0] | default('6') }}-tomcat.fc"
        regexp: '^@@CWD@@'
        replace: "{{ jws_home }}"

    - name: Create selinux policy
      ansible.builtin.command: make -f /usr/share/selinux/devel/Makefile
      args:
        chdir: "{{ jws_home }}/selinux"
        creates: "{{ jws_home }}/selinux/jws{{ jws_version.split('.')[0] | default('6') }}-tomcat.pp"
      when:
        - not policy_path_selinux.stat.exists
      notify:
        - "Selinux policy created"
        - "Apply selinux policy"

    - name: Allow jws to listen to ports
      ansible.builtin.include_tasks: seport.yml
      loop:
        - "{{ jws_listen_http_port }}"
        - "{{ jws_listen_https_port }}"
        - "{{ jws_listen_ajp_port }}"
        - "{{ jws_shutdown_port }}"
      loop_control:
        loop_var: requested_port
