---
- name: Check arguments
  ansible.builtin.assert:
    that:
      - jws.service.name is defined
    quiet: true

- name: "Enable jws.service"
  become: True
  ansible.builtin.service:
    name: "{{ jws.service.name }}"
    enabled: True

- name: "Start jws.service"
  become: True
  ansible.builtin.service:
    name: "{{ jws.service.name }}"
    state: started
