---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: personas
  remote_user: ansible
  become: yes
  vars_files:
    - web_personas_vars.yml
    - secret_vars.yml
  roles:
    - name: jws
