---
#roles:
#  # Install a role from Ansible Galaxy.
#  - name: geerlingguy.java
#    version: "1.9.6" # note that ranges are not supported for roles

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: ">=9.3.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.4"
    source: https://galaxy.ansible.com
