---
- name: "Red Hat JBoss Web Server installation and configuration"
  hosts: trans
  remote_user: ansible
  become: yes
  vars_files:
    - trans_vars.yml
    - secret_vars.yml
  roles:
    - name: jws
