---
- name: "Check if \"{{ packages_list | join(', ') }}\" packages are already installed"  # noqa command-instead-of-module this runs faster
  ansible.builtin.command: "rpm -q {{ packages_list | join(' ') }}"
  register: rpm_info
  changed_when: False
  failed_when: False
- debug:
    msg: "{{ rpm_info.stdout_lines }}"

- name: "Add missing packages to the yum install list"
  ansible.builtin.set_fact:
    #packages_to_install: "{{ packages_to_install | default([]) + rpm_info.stdout_lines | map('regex_findall', 'package (.+) is not installed$') | default([]) | flatten }}"
    packages_to_install: "{{ packages_to_install | default([]) + rpm_info.stdout_lines | map('regex_findall', 'el paquete (.+) no está instalado$') | default([]) | flatten }}"

- name: Verify subscription status
  ansible.builtin.shell: "subscription-manager status"
  register: subscription_status
  ignore_errors: yes

- name: Register as user {{ subscription_user  }} with password (somepass) and auto-subscribe to available content.
  community.general.redhat_subscription:
    state: present
    username: "{{ subscription_user }}"
    password: "{{ subscription_pass }}"
    auto_attach: true
      #force_register: true
  when:
    - subscription_user != ""
    - subscription_pass != ""
    - subscription_status.rc != 0

- name: "Install packages: {{ packages_to_install }}"
  become: True
  ansible.builtin.yum:
    name: "{{ packages_to_install }}"
    state: present
  when: packages_to_install | default([]) | length > 0
