---
- name: "Install Java"
  when:
    - jws_java_home is not defined and jws_java_version is defined
    - ansible_os_family == "RedHat"
  block:
    - name: "Add 'java-{{ jws_java_version }}-openjdk-headless' to dependencies list"
      ansible.builtin.set_fact:
        jws_dependencies_list: "{{ jws_dependencies_list + ['java-{{ jws_java_version }}-openjdk-headless'] }}"

    - name: "Determine JAVA_HOME for selected JVM RPM"
      ansible.builtin.set_fact:
        rpm_java_home: "/etc/alternatives/jre_{{ jws_java_version }}"
