---
- name: Install Jboss Web Server 6
  hosts: all
  remote_user: "ansible"
  become: true
  become_method: sudo
    #gather_facts: false
  vars:
    user: tomcat
  roles:
    #- install_packages
    #- install_jw6
    - cis_hardening
    - so_tuning
